import Link from "next/link";
import { Shell } from "@/components/site-shell";

const modernizationIncludes = ["1–3 primary pages or an equivalent simple scope", "A redesign built from your existing brand and content", "Responsive, mobile-first layout and clearer navigation", "Improved content hierarchy, calls to action, and contact path", "Launch or migration support, with accessibility and performance in mind"];
const careIncludes = ["MSD-managed hosting, SSL, and basic uptime monitoring", "Routine platform and site maintenance", "Small text, image, or contact-information changes within reasonable use", "Practical technical upkeep and support for the live site"];
const scopeDrivers = ["Additional pages or major content rewriting", "New photography or content creation", "Booking, appointment, or complex form integrations", "Ecommerce, portals, or custom functionality", "Substantial rebranding or unusual platform migrations"];
const enhancements = [["Additional pages or content", "For businesses that need more than the starting scope."], ["Booking / appointment integrations", "When a client workflow needs to connect directly to the site."], ["Copy / content support", "For teams that need help refining or rebuilding their story."], ["Seasonal / Event Themes", "Temporary visual themes for holidays, campaigns, events, or special occasions—without redesigning the underlying site."]];

export default function PricingPage() {
  return <Shell><div className="pricing-page">
    <section className="pricing-hero"><div className="wrap"><p className="pricing-kicker">PRICING</p><h1>Simple pricing.<br /><em>No surprises.</em></h1><p className="pricing-hero-copy">Straightforward website modernization starts at $500. Ongoing hosting and maintenance is $50/month. If your site needs more, we define the scope before work begins.</p><div className="pricing-actions"><Link className="pricing-button" href="/contact">Start a Conversation <span>↗</span></Link><a className="pricing-text-link" href="#core-pricing">See What&apos;s Included</a></div></div></section>
    <section className="pricing-core" id="core-pricing"><div className="wrap"><div className="pricing-core-intro"><div><p className="pricing-kicker">CORE PRICING</p><h2>Clear numbers.<br />A practical starting point.</h2></div><p>Two simple parts: the work to modernize your site, and ongoing care to keep it useful after launch.</p></div><div className="pricing-offer-grid"><article className="pricing-modernization"><p className="pricing-offer-label">WEBSITE MODERNIZATION</p><strong>Starting<br />at $500</strong><p className="pricing-offer-summary">A straightforward small-business informational modernization using your existing business content and branding as the foundation.</p><ul>{modernizationIncludes.map(item=><li key={item}>{item}</li>)}</ul><p className="pricing-boundary">The starting price is not an unlimited flat fee. Larger sites, new content, integrations, custom functionality, or broader design needs are scoped before work begins.</p></article><article className="pricing-care"><p className="pricing-offer-label">HOSTING &amp; MAINTENANCE</p><strong>$50<small>/month</small></strong><p className="pricing-offer-summary">MSD-managed hosting and maintenance for the site after it is live.</p><ul>{careIncludes.map(item=><li key={item}>{item}</li>)}</ul><p className="pricing-boundary">Larger redesigns, feature work, and significant content changes are scoped separately—before any additional work begins.</p></article></div></div></section>
    <section className="pricing-included"><div className="wrap pricing-included-grid"><div><p className="pricing-kicker">THE STARTING SCOPE</p><h2>Enough to make the site feel current.</h2></div><div><p>The $500 starting price is designed for established businesses with a straightforward informational site—not a blank slate, and not a complicated software project.</p><div className="pricing-scope-example"><span>TYPICAL STARTING MODERNIZATION</span><b>Existing small-business site</b><p>Three core pages · existing brand and content retained · mobile-first redesign · contact form · launch</p><strong>Starting at $500</strong></div></div></div></section>
    <section className="pricing-scope"><div className="wrap pricing-scope-grid"><div><p className="pricing-kicker">WHEN THE WORK EXPANDS</p><h2>Some websites need more.<br /><em>That&apos;s okay.</em></h2><p>When the work reaches beyond a standard modernization, we define the scope and price before we begin.</p></div><ul>{scopeDrivers.map((item,index)=><li key={item}><span>0{index+1}</span>{item}</li>)}</ul></div></section>
    <section className="pricing-enhancements"><div className="wrap"><div className="pricing-enhancements-heading"><div><p className="pricing-kicker">OPTIONAL ENHANCEMENTS</p><h2>Keep the site useful after launch.</h2></div><p>Useful additions are available when they support how your business actually works. They are priced separately based on complexity.</p></div><div className="pricing-enhancement-grid">{enhancements.map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p>{title === "Seasonal / Event Themes" && <small>Halloween · holiday/winter · local events · business anniversaries · team-inspired or game-day treatments using approved client-provided assets.</small>}</article>)}</div></div></section>
    <section className="pricing-no-surprises"><div className="wrap"><p className="pricing-kicker">SCOPE TRANSPARENCY</p><h2>Know the scope before we build.</h2><p>If the work falls outside the standard modernization starting scope, we define the additional work and price before moving forward. No surprise invoices—and no vague promises.</p></div></section>
    <section className="pricing-final"><div className="wrap"><p className="pricing-kicker">A CLEAR NEXT STEP</p><h2>Have a site in mind?</h2><p>Show us what you have today. We&apos;ll tell you whether it fits the standard modernization scope or needs something more.</p><div className="pricing-actions"><Link className="pricing-button pricing-button-light" href="/contact">Start a Conversation <span>↗</span></Link><Link className="pricing-text-link pricing-text-link-light" href="/website-modernization">Explore Website Modernization</Link></div></div></section>
  </div></Shell>;
}
