import Link from "next/link";
import { Shell } from "@/components/site-shell";

const modernizationIncludes = ["Approximately 1–3 primary pages or an equivalent simple scope", "Existing business branding used as the foundation", "Existing usable content retained where practical", "Modern responsive, mobile-first implementation", "Improved navigation, hierarchy, calls to action, and contact path", "Contact form where appropriate, plus launch or migration support", "Accessibility and performance considered as part of implementation"];
const careIncludes = ["MSD-managed hosting, SSL, and basic uptime monitoring", "Routine site and platform maintenance", "Practical technical upkeep and reasonable support for the live site", "Small text, image, contact-information, or similar minor content changes within reasonable use"];
const scopeDrivers = ["Additional pages or substantial content rewriting", "New photography, substantial copywriting, or content creation", "Custom booking or appointment workflows, complex forms, or third-party integrations", "Ecommerce, portals, or custom functionality", "Substantial rebranding or unusual platform migrations"];
const enhancements = [["Additional pages or content", "For businesses that need more than the starting scope."], ["Booking / appointment integrations", "For businesses that need scheduling or workflow connections beyond a basic contact path."], ["Copy / content support", "For businesses that need substantial help refining, rewriting, or developing their content."], ["Seasonal / Event Themes", "Temporary visual treatments for holidays, campaigns, local events, anniversaries, or game days—without rebuilding the underlying site."]];

export default function PricingPage() {
  return <Shell><div className="pricing-page">
    <section className="pricing-hero"><div className="wrap"><p className="pricing-kicker">PRICING</p><h1>Simple pricing.<br /><em>No surprises.</em></h1><p className="pricing-hero-copy">Straightforward website modernization starts at $500. Ongoing hosting and maintenance is $50/month. If your site needs more, we define the scope before work begins.</p><div className="pricing-actions"><Link className="pricing-button" href="/contact">Start a Conversation <span>↗</span></Link><a className="pricing-text-link" href="#core-pricing">See What&apos;s Included</a></div></div></section>
    <section className="pricing-core" id="core-pricing"><div className="wrap"><div className="pricing-core-intro"><div><p className="pricing-kicker">CORE PRICING</p><h2>Clear numbers.<br />A practical starting point.</h2></div><p>Two simple parts: the work to modernize your site, and ongoing care to keep it useful after launch.</p></div><div className="pricing-offer-grid"><article className="pricing-modernization"><p className="pricing-offer-label">WEBSITE MODERNIZATION</p><strong>Starting<br />at $500</strong><p className="pricing-offer-summary">Best fit for: straightforward small-business informational websites using existing business branding and usable content as the foundation.</p><ul>{modernizationIncludes.map(item=><li key={item}>{item}</li>)}</ul><p className="pricing-boundary">The starting price is not an unlimited flat fee. Larger sites, new content, integrations, custom functionality, or broader design needs are scoped before work begins.</p></article><article className="pricing-care"><p className="pricing-offer-label">HOSTING &amp; MAINTENANCE</p><strong>$50<small>/month</small></strong><p className="pricing-offer-summary">Every MSD-managed site continues with managed hosting and ongoing site care after launch.</p><ul>{careIncludes.map(item=><li key={item}>{item}</li>)}</ul><p className="pricing-boundary">Larger redesigns, new functionality, new pages, or significant content changes are scoped separately before work begins.</p></article></div></div></section>
    <section className="pricing-included"><div className="wrap pricing-included-grid"><div><p className="pricing-kicker">THE STARTING SCOPE</p><h2>A focused modernization can go a long way.</h2></div><div><p>The $500 starting point is designed for established businesses with a straightforward informational site—not a blank-slate brand project or a complex software build.</p><div className="pricing-scope-example"><span>TYPICAL STARTING MODERNIZATION</span><b>Existing small-business website</b><p>Three core pages · existing brand and usable content retained · mobile-first redesign · clear contact path / contact form · launch</p><strong>Starting at $500</strong></div></div></div></section>
    <section className="pricing-scope"><div className="wrap pricing-scope-grid"><div><p className="pricing-kicker">WHEN THE WORK EXPANDS</p><h2>Some websites need more.<br /><em>That&apos;s okay.</em></h2><p>When the work reaches beyond a standard modernization, we define the scope and price before we begin.</p></div><ul>{scopeDrivers.map((item,index)=><li key={item}><span>0{index+1}</span>{item}</li>)}</ul></div></section>
    <section className="pricing-enhancements"><div className="wrap"><div className="pricing-enhancements-heading"><div><p className="pricing-kicker">OPTIONAL ENHANCEMENTS</p><h2>Add what your business actually needs.</h2></div><p>Useful enhancements can be added when they support how your business works. We scope them separately so the core modernization stays simple.</p></div><div className="pricing-enhancement-grid">{enhancements.map(([title,copy],index)=><article className={title === "Seasonal / Event Themes" ? "pricing-seasonal" : ""} key={title}><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p>{title === "Seasonal / Event Themes" && <small><b>SEASONAL / EVENT</b>Examples: Halloween, winter/holiday, local-event, anniversary, and approved/client-provided game-day themes.<br /><i>Priced separately based on complexity.</i></small>}</article>)}</div></div></section>
    <section className="pricing-no-surprises"><div className="wrap"><p className="pricing-kicker">SCOPE TRANSPARENCY</p><h2>Know the scope before we build.</h2><p>If the work falls outside the standard modernization scope, we define the additional work and price before moving forward. If the scope changes during the project, we discuss the change before additional work is performed.</p></div></section>
    <section className="pricing-final"><div className="wrap"><p className="pricing-kicker">A CLEAR NEXT STEP</p><h2>Have a site in mind?</h2><p>Show us what you have today. We&apos;ll tell you whether it fits the standard modernization scope or needs something more.</p><div className="pricing-actions"><Link className="pricing-button pricing-button-light" href="/contact">Start a Conversation <span>↗</span></Link><Link className="pricing-text-link pricing-text-link-light" href="/website-modernization">Explore Website Modernization</Link></div></div></section>
  </div></Shell>;
}
