import Image from "next/image";

const Logo=({size=72}:{size?:number})=><Image className="savages-study-logo" src="/assets/savages-logo.png" alt="Savages Fly Gear" width={size} height={size} priority/>;

function Legacy(){return <main className="savages-legacy"><div className="legacy-site"><header className="legacy-header"><Logo size={98}/><div><p>SAVAGES FLY GEAR</p><small>Streamer flies and gear for serious anglers.</small></div><form aria-label="Site search"><input aria-label="Search" placeholder="Search our site"/><button type="button">Search</button></form></header><nav className="legacy-nav"><span>Home</span><span>Flies</span><span>Gear</span><span>About</span><span>Contact</span></nav><section className="legacy-banner"><Image src="/assets/savages-trout.jpg" alt="Brown trout and streamer fly" fill priority sizes="900px"/><div><h1>Savages Fly Gear</h1><p>Streamer flies and gear for serious anglers.</p><button type="button">View Our Flies</button></div></section><section className="legacy-columns"><article><h2>Welcome to Savages</h2><p>We build and fish streamer flies for anglers who spend their best days on the water. Take a look around and find the gear that belongs in your box.</p><a>Learn more about Savages →</a></article><article><Image src="/assets/savages-flies.jpg" alt="Streamer fly assortment" width={330} height={220}/><h2>Featured Flies</h2><p>Patterns tied for big water, big fish and long casts.</p><button type="button">Shop Flies</button></article><article><h2>Latest from the River</h2><ul><li>How to fish a streamer all day</li><li>The flies we never leave home without</li><li>Where the big fish live</li></ul><Image src="/assets/savages-last-cast.jpg" alt="Last Cast campaign art" width={150} height={225}/></article></section><footer className="legacy-footer">© Savages Fly Gear · Contact us · Follow along on Instagram</footer></div></main>}

function Modern({mobile=false}:{mobile?:boolean}){return <main className={mobile?"savages-modern savages-modern-mobile":"savages-modern"}><header className="modern-header"><div className="modern-lockup"><strong>SAVAGES</strong><span>FLY GEAR</span></div>{!mobile&&<nav><span>Flies</span><span>Gear</span><span>Stories</span><span>About</span></nav>}<div className="modern-badge"><Logo size={mobile?48:54}/>{mobile?<b>MENU</b>:<i>○</i>}</div></header><section className="modern-hero"><div className="modern-hero-image"><Image src="/assets/savages-trout.jpg" alt="Brown trout held beside a streamer fly" fill priority sizes={mobile?"100vw":"60vw"}/><span>01 / THE CHASE</span></div><div className="modern-hero-copy"><p>STREAMER-FOCUSED FLY GEAR</p><h1>CHASE BIG FISH.<br/>THROW BIG FLIES.</h1><span>Streamer-focused flies and gear for anglers who hunt the fish worth remembering.</span><div><button type="button">Shop Streamers <b>↗</b></button><i>#StripStreamers</i></div></div></section><section className="modern-feature"><div><p>BUILT FOR THE GRAB</p><h2>Big flies.<br/>Bigger eats.</h2><span>Flies, gear and stories for the anglers who would rather cast bigger.</span><a>Explore the streamer edit ↗</a></div><div className="feature-image"><Image src="/assets/savages-flies.jpg" alt="Fly boxes filled with streamer flies" fill sizes={mobile?"100vw":"48vw"}/></div></section><section className="modern-story"><div className="story-art"><Image src="/assets/savages-last-cast.jpg" alt="Last Cast Savages campaign art" fill sizes={mobile?"54vw":"25vw"}/></div><div><p>FROM THE RIVER</p><h2>Last cast.<br/>Best story.</h2><span>Fishing culture for the days that stay with you long after the drift.</span><a>Read the field notes →</a></div><Logo size={mobile?78:105}/></section><footer className="modern-footer"><span>SAVAGES FLY GEAR</span><span>Fish hard. Strip streamers.</span><span>© 2026</span></footer></main>}

export function SavagesStudy({kind}:{kind:"legacy"|"modern"|"mobile"}){if(kind==="legacy")return <Legacy/>;return <Modern mobile={kind==="mobile"}/>}
