import Image from "next/image";

const Logo=({size=72}:{size?:number})=><Image className="savages-study-logo" src="/assets/savages-logo.png" alt="Savages Fly Gear" width={size} height={size} priority/>;

function Legacy(){return <main className="savages-legacy"><div className="legacy-site"><header className="legacy-header"><Logo size={98}/><div><p>SAVAGES FLY GEAR</p><small>Streamer flies and gear for serious anglers.</small></div><form aria-label="Site search"><input aria-label="Search" placeholder="Search our site"/><button type="button">Search</button></form></header><nav className="legacy-nav"><span>Home</span><span>Flies</span><span>Gear</span><span>About</span><span>Contact</span></nav><section className="legacy-banner"><Image src="/assets/savages-trout.jpg" alt="Brown trout and streamer fly" fill priority sizes="900px"/><div><h1>Savages Fly Gear</h1><p>Streamer flies and gear for serious anglers.</p><button type="button">View Our Flies</button></div></section><section className="legacy-columns"><article><h2>Welcome to Savages</h2><p>Savages Fly Gear is built for anglers who fish big water and throw big flies. From proven streamer patterns to the gear we use ourselves, everything here is made with serious fishing in mind.</p><a href="#welcome">Learn More »</a></article><article><h2>Featured Flies</h2><p><b>Yellow Dungeon &amp; Olive Sculpin</b><br/>These proven streamer patterns are tied for long casts and hard takes. See what is currently available in the fly shop.</p><a href="#flies">View All Flies »</a></article><article><h2>Latest from the River</h2><small>October 14, 2016</small><p>Five tips for fishing streamers when the water starts to cool. A few simple adjustments can make a slow fall day productive.</p><a href="#river">Read More »</a></article></section><footer className="legacy-footer">© Savages Fly Gear · Contact us · Follow along on Instagram</footer></div></main>}

function Modern({mobile=false}:{mobile?:boolean}){return <main className={mobile?"savages-modern savages-modern-mobile":"savages-modern"}><header className="modern-header"><div className="modern-lockup"><strong>SAVAGES</strong><span>FLY GEAR</span></div>{!mobile&&<nav><span>Flies</span><span>Gear</span><span>Stories</span><span>About</span></nav>}<div className="modern-badge"><Logo size={mobile?48:54}/>{mobile?<b>MENU</b>:<i>○</i>}</div></header><section className="modern-hero"><div className="modern-hero-image"><Image src="/assets/savages-trout.jpg" alt="Brown trout held beside a streamer fly" fill priority sizes={mobile?"100vw":"60vw"}/><span>01 / THE CHASE</span></div><div className="modern-hero-copy"><p>STREAMER-FOCUSED FLY GEAR</p><h1>CHASE BIG FISH.<br/>THROW BIG FLIES.</h1><span>Streamer-focused flies and gear for anglers who hunt the fish worth remembering.</span><div><button type="button">Shop Gear <b>↗</b></button><i>#StripStreamers</i></div></div></section><section className="modern-feature"><div><p>THE STREAMER VAULT / 01</p><h2>Big flies.<br/>Bigger eats.</h2><span>Purpose-built patterns for the next hard pull.</span><a href="#collection">Explore the collection ↗</a></div><div className="feature-image"><Image src="/assets/savages-flies.jpg" alt="A curated selection of streamer flies" fill sizes={mobile?"100vw":"48vw"}/></div></section><section className="modern-story"><div className="story-art"><Image src="/assets/savages-flies.jpg" alt="Streamer fly collection" fill sizes={mobile?"54vw":"25vw"}/></div><div><p>THE STREAMER VAULT / 02</p><h2>Built to<br/>move water.</h2><span>Purpose-built patterns, fly-tying details, and the field stories behind the next hard pull.</span><a href="#collection">Explore the collection ↗</a></div><Logo size={mobile?78:105}/></section><footer className="modern-footer"><span>SAVAGES FLY GEAR</span><span>Fish hard. Strip streamers.</span><span>© 2026</span></footer></main>}

export function SavagesStudy({kind}:{kind:"legacy"|"modern"|"mobile"}){if(kind==="legacy")return <Legacy/>;return <Modern mobile={kind==="mobile"}/>}
