import Link from "next/link";
import { Shell } from "@/components/site-shell";
import { SavagesStudy } from "@/components/savages-study";

const evaluate=["Mobile experience","Navigation","Content hierarchy","Calls to action","Visual credibility","Imagery","Structure","Technical condition"];
const change=["Responsive layout and mobile-first hierarchy","Navigation, contact paths, and CTA placement","Typography, spacing, image treatment, and content organization","Modern page structure, performance cleanup, and accessibility fundamentals"];
const keep=["Recognizable branding and business personality","Useful content, proven messaging, and existing photography","Your domain, customer familiarity, and search value where practical"];
export function WebsiteModernizationPage(){return <Shell><div className="wm-page">
<section className="wm-decision-hero"><div className="wrap"><p className="wm-eyebrow">WEBSITE MODERNIZATION</p><h1>Does your website need to be replaced —<br/><em>or does it just need to catch up?</em></h1><p>Most established businesses don&apos;t need to start over. We identify what still works, what gets in the customer&apos;s way, and where modernization will make the biggest difference.</p><div><Link className="wm-button focus-ring" href="/contact">Start a Conversation <span>↗</span></Link><Link className="wm-text-link focus-ring" href="/pricing">See Pricing</Link></div><aside><span>WHAT STILL WORKS</span><i>→</i><span>WHAT NEEDS TO CATCH UP</span></aside></div></section>
<section className="wm-fit"><div className="wrap"><p className="wm-eyebrow">THE DECISION</p><h2>You probably don&apos;t need to start over if...</h2><div className="wm-fit-grid"><article><p>A strong modernization candidate</p>{["Your business and brand are still relevant.","Most of the site content is useful.","Customers already know the company and domain.","The core purpose is right; presentation and usability have fallen behind."].map((x,i)=><div key={x}><b>0{i+1}</b>{x}</div>)}</article><article><p>When we should scope something larger</p>{["The business model or brand is fundamentally changing.","You need complex ecommerce, applications, portals, or workflows.","Content must be rebuilt from scratch.","Major transactional or custom functionality is required."].map((x,i)=><div key={x}><b>0{i+1}</b>{x}</div>)}<small>Those projects deserve separate scoping beyond the standard modernization offer.</small></article></div></div></section>
<section className="wm-evaluate"><div className="wrap"><div><p className="wm-eyebrow">WHAT WE LOOK AT</p><h2>We start with the experience you already have.</h2><p>Before deciding what to change, we look at how a real customer encounters your current site.</p></div><ol>{evaluate.map((x,i)=><li key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span><small>{["Does it work naturally on a phone?","Can people find what they came for?","Is the important information obvious?","Can someone take the next step without searching?","Does the site represent the business today?","Are photos doing useful work?","Is the site clear to maintain?","Are there obvious performance or compatibility issues?"][i]}</small></li>)}</ol></div></section>
<section className="wm-work"><div className="wrap"><p className="wm-eyebrow">WHAT WE CHANGE</p><h2>Modernization is more than a new coat of paint.</h2><div>{change.map((x,i)=><article key={x}><b>0{i+1}</b><p>{x}</p></article>)}</div></div></section>
<section className="wm-preserve"><div className="wrap"><div><p className="wm-eyebrow">WHAT WE KEEP</p><h2>The goal isn&apos;t to erase what already works.</h2></div><div>{keep.map((x,i)=><p key={x}><b>0{i+1}</b>{x}</p>)}<span>Then we build a clearer, faster experience around those assets.</span></div></div></section>
<section className="wm-proof wm-proof-rebuild"><div className="wrap"><div className="wm-proof-heading"><p className="wm-eyebrow">MODERNIZATION IN PRACTICE</p><h2>Same business. A much better experience.</h2><p>We kept the recognizable Savages identity and rebuilt the experience around clearer hierarchy, stronger imagery, and mobile-first design.</p></div><div className="wm-proof-stage"><article className="wm-proof-legacy"><p>BEFORE / LEGACY</p><div className="wm-proof-legacy-view"><SavagesStudy kind="legacy" embedded/></div></article><div className="wm-proof-arrow" aria-label="Legacy Savages Fly Gear website modernized into a responsive experience">→</div><article className="wm-proof-modern"><p>MODERNIZED</p><div className="wm-proof-modern-view"><SavagesStudy kind="modern" embedded/></div><div className="wm-proof-phone"><span>MOBILE FIRST</span><div><SavagesStudy kind="mobile" embedded/></div></div></article></div></div></section>
<section className="wm-starting"><div className="wrap"><p className="wm-eyebrow">STARTING SCOPE</p><h2>A straightforward modernization can stay straightforward.</h2><div><article><b>Website Modernization</b><strong>Starting at $500</strong><span>For a straightforward small-business informational site—typically 1–3 primary pages or equivalent simple scope.</span></article><article><p>Typical starting scope</p><span>Existing brand and content as a foundation, a modern responsive redesign, mobile-first implementation, a contact/conversion path, and launch or migration support.</span></article></div></div></section>
<section className="wm-larger"><div className="wrap"><div><p className="wm-eyebrow">WHEN WE SCOPE MORE</p><h2>Some websites need more than a refresh.</h2></div><div><p>Larger multi-page sites, significant content development, integrations, complex forms, ecommerce, portals, custom functionality, and substantial brand redesign all deserve a defined scope and price before work begins.</p><Link className="wm-text-link focus-ring" href="/pricing">See Pricing <span>→</span></Link></div></div></section>
<section className="wm-final"><div className="wrap"><p className="wm-eyebrow">NEXT STEP</p><h2>Not sure what your current site really needs?</h2><p>Show us the website you&apos;ve outgrown. We&apos;ll help you determine whether it needs a focused modernization or something more substantial.</p><div><Link className="wm-button focus-ring" href="/contact">Start a Conversation <span>↗</span></Link><Link className="wm-text-link focus-ring" href="/pricing">See Pricing</Link></div></div></section>
</div></Shell>}
